---
# tasks file for kubernetes-prerequisites
- name: "Disabling Swap on all nodes"
  shell: swapoff -a

- name: "Commenting Swap entries in /etc/fstab"
  replace:
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

- name: "Adding Kubernetes repository repo file"
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: "Installing required packages"
  dnf:
    name: "{{ packages }}"
    state: present

- name: "Removing unnecessary packages"
  dnf: 
    name: "{{ unnecessary_packages }}"
    state: absent

- name: "Installing Docker"
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum install docker-ce docker-ce-cli containerd.io -y --nobest

- name: "Starting and Enabling the required services"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"

- name: "Allow masquerading in Firewalld"
  firewalld:
    masquerade: "yes"
    state: enabled
    permanent: yes
    immediate: yes

- name: "Creating Bridge Firewall Rule for Kubernetes"
  shell: |
    cat <<_EOF_ > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables=1
    net.bridge.bridge-nf-call-iptables=1
    _EOF_

- name: "Applying sysctl file config"
  shell: sysctl --system

- name: "Applying newly created kubernetes config file"
  shell: sysctl -p /etc/sysctl.d/k8s.conf

