---
- name: "Playbook 7 - Play1 - Set Haproxy"
  hosts: proxy
  vars_files:
    - haproxy-vars.yaml
  tasks:
  - name: "Instalacja HAProxy"
    dnf:
      state: latest
      name:
        - haproxy
  
  - name: "Test istnienia pliku"
    stat:
      path: /etc/haproxy/haproxy.cfg-orig
    register: stat_haproxy_cfg

  - name: "Przeniesienie konfiga oryginalnego"
    command: "mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg-orig"
    when: stat_haproxy_cfg.stat.exists == False

  - name: "Kopiowanie HAProxy konfiga"
    template:
      src: files/haproxy-cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: '0644'
      owner: root
      group: root
      backup: yes

  - name: "Start Firewall"
    service:
      name: firewalld
      state: started
      enabled: true

  - name: "Dziurka w firewall - 80"
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      immediate: yes  

  - name: "Uruchomienie HAProxy"
    systemd:
      name: haproxy
      state: started
      enabled: yes

...
