---
- name: "Playbook 8 - Play1 - Install soft"
  hosts: lan_hosts
  tasks:
  - name: "Instalacja pakietow"
    dnf:
      state: latest
      name:
        - mc
        - strace
        - vim
    when:
      - inventory_hostname in groups ['www']
      - ansible_facts['nodename'] == 'node2'
      - ansible_facts['os_family'] == 'RedHat'
      - ansible_facts['distribution_major_version'] == '7'
