---
- name: "Playbook 20 - Localhost Play"
  hosts: localhost
  tasks:
  - name: "Generate Facts Data"
    shell: 
      cmd: |
        ansible -m setup -i inventory --tree ansiblecmdb/ infra
    become: yes
    become_user: root
    remote_user: vagrant

  - name: "Generate CMDB Page"
    shell: 
      cmd: |
       ansible-cmdb -t html_fancy  ansiblecmdb/ > ansiblecmdb.html

- name: "Playbook 20 - WWW Play"
  hosts: www
  tasks:
  - name: "Copy CMDB webpage"
    copy:
      src: ansiblecmdb.html
      dest: /var/www/html/ansiblecmdb.html
      user: root
      group: root
      mode: '0644'
...
