---
# tasks file for tomcat
- name: "Installing OpenJDK"
  dnf:
    name: '{{ java_ver }}'
    state: latest

- name: "Add Tomcat Group"
  group:
    name: tomcat

- name: "Add Tomcat User"
  user:
    name: tomcat
    group: tomcat
    home: /home/tomcat
    createhome: no

- name: "Create directory for Tomcat"
  file:
    path: '{{ tomcat_dir }}'
    state: directory
    mode: '0755'

- name: "Copy Tomcat Installation File"
  copy:
    src: '{{ tomcat_inst_file }}'
    dest: /tmp/{{ tomcat_inst_file }}

- name: "File checksum"
  stat:
    path: /tmp/{{ tomcat_inst_file }}
  register: tomcat_inst_md5sum

- debug:
    var: tomcat_inst_md5sum.stat.md5

- name: "Dir test"
  stat:
    path: '{{ tomcat_dir }}'
  register: stat_tomcat_dir

- name: "Unarchive Tomcat Installation File"
  unarchive:
    src: /tmp/{{ tomcat_inst_file }}
    dest: '{{ tomcat_dir }}'  
    remote_src: yes
  when: stat_tomcat_dir.stat.exists == False

- name: "Change ownership"
  file:
    path: '{{ tomcat_dir }}'
    owner: tomcat
    group: tomcat
    recurse: yes
    state: directory

- name: "Create symbolic link to current Tomcat"
  file:
    src: '{{ tomcat_dir }}/{{ tomcat_ver }}'
    dest: '{{ tomcat_dir }}/current'
    state: link

- name: "Copy Tomcat service file"
  template:
    src: tomcat-service.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0755'

- name: "Open Firewall port for Tomcat"
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: true  

- name: "Start and enable Tomcat Service"
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: yes




































