---
- name: "Playbook 1 - Play1"
  hosts: www, proxy
  become: yes
  become_user: root

  tasks:
  - name: "Instalacja pakietow"
    dnf:
      state: latest
      name:
        - mc
        - nano
  - name: "Usuniecie pakietu"
    dnf:
      state: absent
      name: nano
...
