---
- name: "Playbook 6 - Play1 - Custom Facts"
  hosts: www
  vars:
    remote_facts_dir: /etc/ansible/facts.d
    facts_file: files/custom.fact
  tasks:
  - name: "Create remote facts dir"
    file:
      state: directory
      recurse: yes
      path: "{{ remote_facts_dir }}"

  - name: "Copy new fact"
    copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_facts_dir }}"
...
