---
- name: "Palybook 10 - Play1 - Selinux"
  hosts: www
  tasks:
  - name: "Turn on SELinux"
    replace:
      path: /etc/selinux/config
      regexp: 'SELINUX=disabled'
      replace: 'SELINUX=enforcing'
    notify: "host reboot"

  handlers:
  - name: "host reboot"
    reboot:  
...
