---
- name: "Playbook 11 - Play1 - Block in File"
  hosts: www
  tasks:
  - name: "Test - file1 exists? "
    stat:
      path: /tmp/plik1
    register: plik1_test

  - name: "Creating file1"
    file:
      path: /tmp/plik1
      state: touch
    when: plik1_test

  - name: "Test - file2 exists? "
    stat:
      path: /tmp/plik2
    register: plik2_test

  - name: "Creating file2"
    file:
      path: /tmp/plik2
      state: touch
    when: plik2_test

  - name: "Write to file1"
    blockinfile:
      path: /tmp/plik1
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->" 
      block: |
        Litwo 
        ojczyzno
        moja
        ty jestes jak ...

  - name: "Write to file2"
    blockinfile:
      path: /tmp/plik2
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: >
        Litwo
        ojczyzno
        moja
        ty jestes jak ...
...
