---
- name: "Playbook 11 - Play1 - Block in File"
  hosts: www
  tasks:
  - name: "Test pliku1"
    stat:
      path: /tmp/plik1
    register: plik1_test

  - name: "Utworz plik"
    file:
      path: /tmp/plik1
      state: touch
    when: plik1_test

  - name: "Test pliku2"
    stat:
      path: /tmp/plik2
    register: plik2_test

  - name: "Utworz plik"
    file:
      path: /tmp/plik2
      state: touch
    when: plik2_test

  - name: "Zapis do pliku 1"
    blockinfile:
      path: /tmp/plik1
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->" 
      block: |
        Litwo 
        ojczyzno
        moja
        ty jestes jak ...

  - name: "Zapis do pliku 2"
    blockinfile:
      path: /tmp/plik2
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: >
        Litwo
        ojczyzno
        moja
        ty jestes jak ...






















